/* eslint-disable */
/**
 * TEMPORARY STUB FILE
 *
 * This file will be automatically generated by Convex once you connect your deployment.
 *
 * To connect your existing Convex deployment:
 * 1. Make sure NEXT_PUBLIC_CONVEX_URL is set in environment variables (Vars section in sidebar)
 * 2. Run `npx convex dev` in your terminal to sync the schema and generate this file
 *
 * Your Convex deployment URL from the dashboard you shared:
 * https://dashboard.convex.dev/t/jeremiah-and-lacey-anderson/treeshop-astro/watchful-jackal-831
 */

declare const api: any
export { api }
